<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <joint name="$(arg robot_name)_laser_joint" type="fixed">
        <parent link="$(arg robot_name)_chassis"/>
        <child link="$(arg robot_name)_laser_frame"/>
        <origin xyz="0.07 0 ${(chassis_height + wheel_length)/2}" rpy="0 0 0"/>
    </joint>

    <link name="$(arg robot_name)_laser_frame">
        <visual>
            <geometry>
            <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
            <geometry>
                <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="0.1"/>
            <inertia ixx="2.53e-4" iyy="2.53e-4" izz="5e-4" ixy="0" ixz="0" iyz="0"/>
        </inertial>
    </link>

    <gazebo reference="$(arg robot_name)_laser_frame">
        <material>Gazebo/Red</material>

        <sensor name="$(arg robot_name)_laser" type="ray">
            <pose> 0 0 0 0 0 0 </pose>
            <visualize>true</visualize>
            <update_rate>10</update_rate>
            <ray>
                <scan>
                    <horizontal>
                        <samples>360</samples>
                        <min_angle>-3.14</min_angle>
                        <max_angle>3.14</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>0.3</min>
                    <max>12</max>
                </range>
            </ray>
            <plugin name="$(arg robot_name)_laser_controller" filename="libgazebo_ros_ray_sensor.so">
                <ros>
                    <argument>~/out:=scan</argument>
                </ros>
                <output_type>sensor_msgs/LaserScan</output_type>
                <frame_name>$(arg robot_name)_laser_frame</frame_name>
            </plugin>
        </sensor>
    </gazebo>

</robot>