robot_2:
  controller_manager:
    ros__parameters:
      update_rate: 30
      use_sim_time: true

      diff_cont:
        type: diff_drive_controller/DiffDriveController

      joint_broad:
        type: joint_state_broadcaster/JointStateBroadcaster
      
  diff_cont:
    ros__parameters:

      publish_rate: 30.0

      base_frame_id: robot_2_base_link

      left_wheel_names: ['robot_2_left_front_wheel_joint']
      right_wheel_names: ['robot_2_right_front_wheel_joint']
      wheel_separation: 0.22
      wheel_radius: 0.035

      use_stamped_vel: false

      # command_interfaces: ['velocity']
      # state_interfaces: ['velocity', 'position']